/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

#line 1 "ternop1.c"
typedef int __int32_t;
#line 3
extern  __attribute__((__nothrow__)) __int32_t const   **( __attribute__((__leaf__)) __ctype_tolower_loc)(void)  __attribute__((__const__)) ;
#line 6
__inline extern  __attribute__((__nothrow__)) int ( __attribute__((__leaf__, __gnu_inline__)) tolower)(int __c ) ;
#line 6 "ternop1.c"
__inline extern int ( __attribute__((__leaf__, __gnu_inline__)) tolower)(int __c ) 
{ 
  __int32_t const   **tmp ;
  __int32_t tmp___0 ;

  {
#line 9
  if (__c >= -128) {
#line 9
    if (__c < 256) {
      {
#line 9
      tmp = __ctype_tolower_loc();
#line 9
      tmp___0 = *(*tmp + __c);
      }
    } else {
#line 9
      tmp___0 = (__int32_t const   )__c;
    }
  } else {
#line 9
    tmp___0 = (__int32_t const   )__c;
  }
#line 9
  return ((int )tmp___0);
}
}
